%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/dobi/transfer/inz/charger-v2/source/hil/log/ident_200115_12-20-25_data60s.tsv
%
% Auto-generated by MATLAB on 15-Jan-2020 16:42:56

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Is", "t_Is", "Ir", "t_Ir", "Vc", "t_Vc"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

file = 'ident_200117_23-25-53_now_really';
% Import the data
d = readtable(['/home/dobi/transfer/inz/charger-v2/source/hil/log/' file '.tsv'], opts);

% Is = timeseries(d.Is, d.t_Is/1000);
% Ir = timeseries(d.Ir, d.t_Ir);
% Vc = timeseries(d.Vc, d.t_Vc);

clear opts 

